# Generated by Django 4.2 on 2023-04-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tages',
            field=models.ManyToManyField(related_name='articles', through='articles.Scope', to='articles.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Раздел'),
        ),
    ]
