# Generated by Django 4.2 on 2023-04-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_tages_tag_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['-is_main', 'tag'], 'verbose_name': 'Тематика статьи', 'verbose_name_plural': 'Тематика Статей'},
        ),
    ]
